<?php
/********************************************************************************
    Contains code common to several D6 classes.
    
    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    @history    2019-06-07, Thierry Graff : Creation
********************************************************************************/
namespace g5\commands\gauq\D6;

class D6{
    
    // TRUST_LEVEL not defined, using value of class Cura
    
    /** Fields of data/raw/gauq/lerrcp/D6.csv **/
    const RAW_FIELDS = [
        'NUM',
        'DAY',
        'MON',
        'YEA',
        'H',
        'MN',
        'SEC',
        'LAT',
        'LON',
        'NAME',
    ];

    /** Fields of data/tmp/gauq/lerrcp/D6.csv **/
    const TMP_FIELDS = [
        'NUM',
        'FNAME',
        'GNAME',
        'OCCU',
        'DATE',
        'PLACE',
        'CY',
        'C2',
        'GEOID',
        'LG',
        'LAT',
    ];
    
    /**
        Human corrections for given names.
        Generated by look::execute_emptyGiven() and modified by a human.
        Format : NUM => [family name, given name]
        Notes :
            - corrections marked with // ??? are suppositions that may introduce errors.
            - corrections on names starting by 'Mc' and 'Van' were done without checking on the web (may also introduce errors).
        Logically, these corrections should be located in a yaml tweak file.
    **/
    const NAMES_CORRECTIONS = [
        '1'   => ['Adamczyk', 'Marcel'],
        '67'  => ['Gordon Hutton', 'Bremner'],
        '113' => ['von Cramm', 'Gottfried'], // Gottfried Alexander Maximilian Walter Kurt Freiherr von Cramm !!!
        '115' => ['Crossalexander', ''], // ???
        '119' => ['Darui', 'Julien'],
        '124' => ['de Haan', 'Johannes'],
        '128' => ['de Michèle', 'Gabriel'],
        '129' => ['de Nadaï', 'Francis'], // Paul-François de Nadaï dit Francis de Nadaï
        '130' => ['den Hartog', 'Arie'],
        '131' => ['den Hartog', 'Fedor'],
        '132' => ['de Shoemmacker', 'Joseph'],
        '133' => ['Desmet', 'Armand'],
        '138' => ['Di Nallo', 'Fleury'],
        '181' => ['Maria Francisca', 'Gommers'], // Maria ("Mia") Francisca Philomena Hoogakker-Gommers
        '189' => ['Grim', 'Joe'], // Joe Grim (born Saverio Giannone)
        '212' => ['Barclay', 'Joyce'], // Joyce Barclay successivement épouse Williams, Hume, Engelfield, Sacerdote et Bennett
        '228' => ['Kemper', 'Franz-Joseph'],
        '229' => ['Koczur', 'Ferenc'], // Ferenc Koczur ou Frans Koczur dit Koczur Ferry
        '247' => ['Le Chenadec', 'Gilbert'],
        '265' => ['Mc Calliog', 'Jim'],
        '266' => ['Mc Cormick', 'John'],
        '267' => ['Mc Creadie', 'Eddie'],
        '268' => ['Mc Govern', 'John'],
        '269' => ['Mc Gowan', 'Walter'],
        '289' => ['Mildenberger', 'Karl'],
        '368' => ['Schnellinger', 'Karl-Heinz'],
        '401' => ['Urtain', 'José Manuel'], // José Manuel Ibar Azpiazu, plus connu comme Urtain
        '403' => ['Van Impe', 'Lucien'],
        '404' => ['Van Linden', 'Rik'],
        '405' => ['Van Tygem', 'Noel'], // ???
        '415' => ['De Vlaeminck', 'Roger'],
        '424' => ['Winkler', 'Hans Günter'],
        '442' => ['Jouve', 'Roger-Louis'], // ???
    ];
    
} // end class    
