<?php
/********************************************************************************
    Code to examine 5-tmp/g55/570SPO.csv
    (not the raw file, the intermediate file generated by raw2csv.php).
    Not part of any build process - only to try to understand.
    
    To add a new function : 
        - add entry in POSSIBLE_PARAMS
        - implement a method named "examine_<entry>"
    
    @license    GPL
    @history    2019-05-26 00:33:22+02:00, Thierry Graff : addition to new structure
********************************************************************************/
namespace g5\transform\g55\spo570;

use g5\init\Config;
use g5\patterns\Command;

class examine implements Command {
    
    // *****************************************
    /** 
        Routes to the different actions, based on $param
        @param $param Array containing one element (a string)
                      Must be one of self::POSSIBLE_PARAMS
    **/
    public static function execute($params=[]): string{
    }
    
        
}// end class
