

# nb of humans in wikidata
# 2019-05-22 23:21:15+02:00 -> 5082509
SELECT (COUNT(?item) AS ?count)
WHERE {
	?item wdt:P31/wdt:P279* wd:Q5  .
}

sexual identity of subject:
male (Q6581097),
female (Q6581072),
intersex (Q1097630),
transgender female (Q1052281),
transgender male (Q2449503).
Animals:
male animal (Q44148),
female animal (Q43445)