<?php
/********************************************************************************
    Code to examine data/tmp/muller/afd3-women/muller-afd3-women.csv
    (not the raw file, the intermediate file generated by raw2tmp.php).
    Not part of any build process - only to try to understand.
    
    To add a new function : 
        - add <entry> in POSSIBLE_PARAMS
        - implement a method named "look_<entry>"
    
    @license    GPL
    @history    2021-04-11, Thierry Graff : Creation
********************************************************************************/
namespace g5\commands\muller\afd3;

use g5\patterns\Command;
use g5\commands\cura\Cura;
use tiglib\arrays\sortByKey;

class look implements Command {
    
    /** 
        Possible values of the command, for ex :
        php run-g5.php muller afd3 look gauquelin
    **/
    const POSSIBLE_PARAMS = [
        'gauquelin',
    ];
    
    // *****************************************
    /** 
        Routes to the different actions, based on $param
        @param $params Array
                       First element indicates which method execute ; must be one of self::POSSIBLE_PARAMS
                       Other elements are transmitted to the called method.
                       (Called methods are responsible to handle their params).
    **/
    public static function execute($params=[]): string{
        $possibleParams_str = implode(', ', self::POSSIBLE_PARAMS);
        if(count($params) == 0){
            return "PARAMETER MISSING\n"
                . "Possible values for parameter : $possibleParams_str\n";
        }
        $param = $params[0];
        if(!in_array($param, self::POSSIBLE_PARAMS)){
            return "INVALID PARAMETER\n"
                . "Possible values for parameter : $possibleParams_str\n";
        }
        
        $method = 'look_' . $param;
        
        if(count($params) > 1){
            array_shift($params);
            return self::$method($params);
        }
        
        return self::$method();
    }
    
    
    // ******************************************************
    /**
        Count the number of lines present in Gauquelin data
        Checks columns SOURCE and GQ
    **/
    private static function look_gauquelin(){
        $report = '';
        $data = AFD3::loadTmpFile();
        $N = count($data);
        $NG = 0;
        $NStrange = 0;
        $reportStrange = '';
        foreach($data as $line){
            if($line['GQ'] == 'G'){
                $NG++;
            }
            else{
                if(strpos($line['SOURCE'], 'G') !== false){
                    $reportStrange .=  "  {$line['SOURCE']} {$line['GQ']} {$line['MUID']} {$line['NAME']} {$line['DATE']} {$line['OCCU']} \n";
                    $NStrange++;
                }
            }
        }
        $report .= "$NStrange strange lines: not marked 'G' but field SOURCE contains 'G'\n";
        $report .= $reportStrange;
        $report .= "$NG lines marked 'G'\n";
        $NNoG = $N - $NG;
        $report .= "$NNoG lines not marked 'G'\n";
        return $report;
    }
    
    
}// end class
