<?php
/********************************************************************************
    Generation of the original groups published in Gauquelin's book in 1955
    Uses class Data1955, which is generated by tools/generate-1955.php
    The process is :
    - generate serie A csv files (php run-gauquelin5 A)
    - modify the csv file manually, adding a column named '1955'
    - generate class Data1955 with tools/generate-1955.php
    - generate the 1955 groups using this class php run-gauquelin5 1955)
    
    @license    GPL
    @history    2017-05-08 23:39:19+02:00, Thierry Graff : creation
********************************************************************************/
namespace gauquelin5;

use gauquelin5\Gauquelin5;
use gauquelin5\Serie1955Data;
use gauquelin5\init\Config;

class Serie1955{
    
    const CSV_SEP_LIBREOFFICE = ','; // grrrr, libreoffice transformed ; in ,
    
    /**
        1955 groups ; format : group code => [name, serie]
        serie is 'ZZ' for groups that can't be found in cura data
    **/
    const GROUPS_1955 = [
        '576MED' => ["576 membres associés et correspondants de l'académie de médecine", 'A2'],
        '508MED' => ['508 autres médecins notables', 'A2'],
        '570SPO' => ['570 sportifs', 'A1'],
        '676MIL' => ['676 militaires', 'A3'],
        '906PEI' => ['906 peintres', 'A4'],
        '361PEI' => ['361 peintres mineurs', 'ZZ'],
        '500ACT' => ['500 acteurs', 'A5'],
        '494DEP' => ['494 députés', 'A5'],
        '349SCI' => ["349 membres, associés et correspondants de l'académie des sciences", 'A2'],
        '884PRE' => ['884 prêtres', 'ZZ'],
    ];

    
    // *****************************************
    /** 
        Generates the csv files in 6-1955-final/ from csv files located in 5-1955-modified/
        See README in generated file for a meaning of generated fields
        
        Called by : php run-gauquelin5.php 1955 finalize
        
        @param  $serie  String must be '1955' - useless but kept for conformity with other classes
        @return report
        @throws Exception if unable to parse
    **/
    public static function finalize($serie){
        $src_dir = Config::$data['dirs']['5-1955-modified'];
        $dest_dir = Config::$data['dirs']['6-1955-final'];
        $files = glob($src_dir . DS . '*.csv');
        $generatedFields = [
            'ORIGIN',
            'NUM',
            'FIRSTNAME',
            'LASTNAME',
            'PRO',
            'DATE',
            'PLACE',
            'COU',
            'ADM2',
            'LON',
            'LAT',
        ];
        if(Config::$data['dirs']['3-cura-modified']){
            $generatedFields[] = 'GEONAMEID';
        }
        $firstline = implode(Gauquelin5::CSV_SEP, $generatedFields);
        foreach($files as $file){
            $res = $firstline . "\n";
            $groupCode = str_replace('.csv', '', basename($file));
            $lines = file($file, FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
            array_shift($lines); // line containing field names
            foreach($lines as $line){
                $cur = [];
                $fields = explode(self::CSV_SEP_LIBREOFFICE, $line);
                //
                $cur['ORIGIN'] = $fields[1];
                $cur['NUM'] = $fields[2];
                // name
                $tmp = explode(' ', $fields[3]);
                if(count($tmp) != 2){
                    // can happens for 2 cases :
                    // - persons not in cura files and added by a human
                    // - persons with composed last names
                    // In both cases, FIRST55 and LAST55 should be filled
                    if($fields[11] == '' || $fields[12] == ''){
                        echo "ANOMALY ON NAMES - {$cur['NUM']} - LINE SKIPPED, MUST BE FIXED\n";
                        continue;
                    }
                    else{
                        $family = $fields[11];
                        $given = $fields[12];
                    }
                }
                else{
                    [$family, $given] = explode(' ', $fields[3]);
                    // If FIRST55 or LAST55 are filled, override cura value
                    if($fields[11] != ''){
                        $family = $fields[11];
                    }
                    if($fields[12] != ''){
                        $given = $fields[12];
                    }
                }
                $cur['FAMILYNAME'] = $family;
                $cur['GIVENNAME'] = $given;
                // profession
                if($fields[20] != ''){
                    $cur['PRO'] = $fields[20];
                }
                else{
                    $cur['PRO'] = $fields[4];
                }
                // place processed before date to find timezone from geonames
                // but date is put before the date in resulting line
                if($fields[16] != ''){
                    $place = $fields[16]; // priority to geonames
                }
                else if($fields[15] != ''){
                    $place = $fields[15]; // then place manually entered
                }
                else{
                    $place = $fields[6]; // then place manually entered
                }
                if($fields[18] != ''){
                    $country = $fields[18];
                }
                else{
                    $country = $fields[7];
                }
                if($fields[17] != ''){
                    $admin2 = $fields[17];
                }
                else{
                    $admin2 = $fields[8];
                }
                if($admin2 == 'NONE'){
                    $admin2 = '';
                }
                if(strlen($admin2) == 1 && $country == 'FR'){
                    $admin2 = '0' . $admin2; // because libreoffice "eats" the trailing 0
                }
                // HERE try to match Geonames
                $slug = \lib::slugify($place);
                $geonames = \Geonames::match([
                    'slug' => $slug,
                    'countries' => [$country],
                    'admin2-code' => $admin2,
                ]);
                if($geonames){
                }
                else{
                    echo "COULD NOT MATCH GEONAMES - {$cur['NUM']} - $slug $admin2 - LINE SKIPPED, MUST BE FIXED\n";
//echo "\n<pre>"; print_r($geonames); echo "</pre>"; exit;
if($cur['NUM'] != '814') $exit;
                    continue;
                }
            }
/* 
    [0] => G55
    [1] => ORIGIN
    [2] => NUM
    [3] => NAME
    [4] => PRO
    [5] => DATE
    [6] => PLACE
    [7] => COU
    [8] => COD
    [9] => LON
    [10] => LAT
    [11] => FIRST55
    [12] => LAST55
    [13] => HOUR55
    [14] => DATE55
    [15] => PLACE55
    [16] => PLACE_GEO
    [17] => COD_GEO
    [18] => COU_GEO
    [19] => NOTES55
    [20] => PRO55
*/
        }
    }
    
    // *****************************************
    /** 
        Generates the 1955 files in 4-1955-generated/ from :
        - csv files located in 2-cura-exported/
        - csv files located in 3-cura-modified/
        Takes an exact copy of files in 2-cura-exported
        Uses files from 3-cura-modified to filter and dispatch in different resulting files
        Adds a column ORIGIN
        
        Called by : php run-gauquelin5.php 1955 modified21955
        
        @param  $serie  String must be '1955' - useless but kept for conformity with other classes
        @return report
        @throws Exception if unable to parse
    **/
    public static function modified21955($serie){
        $src_dir = Config::$data['dirs']['3-cura-modified'];
        $dest_dir = Config::$data['dirs']['4-1955-generated'];
        
        $groups55 = self::loadGroups3($src_dir);
        
        foreach(self::GROUPS_1955 as $groupCode => [$groupName, $serie]){
            if(count($groups55[$groupCode]) == 0){
                continue; // for groups not treated yet
            }
            echo "Generating 1955 group $groupCode : $groupName\n";
            $res = [];
            $inputfile = Config::$data['dirs']['2-cura-exported'] . DS . $serie . '.csv'; // file generated by class SerieA
            $input = file($inputfile);
            $N = count($input);
            $fieldnames = explode(Gauquelin5::CSV_SEP, $input[0]);
            for($i=1; $i < $N; $i++){
                $fields = explode(Gauquelin5::CSV_SEP, $input[$i]);
                $NUM = $fields[0]; // by convention, all generated csv file of 2-cura-exported have NUM as first field
                if(!in_array($NUM, $groups55[$groupCode])){
                    continue;
                }
                $res[] = $fields;
            }
            //
            // sort $res
            //
            // here simplification : files 2-cura-exported/A1.csv and A2.csv
            // have first field = NUM and second field = NAME
            $sort_field = (Config::$data['1955']['sort'][$groupCode] == 'NUM' ? 0 : 1);
            $res = \lib::sortByKey($res, $sort_field);
            echo '  ' . count($res) . " persons stored\n";
            // generate output
            $output = 'ORIGIN' . Gauquelin5::CSV_SEP . $input[0]; // field names
            foreach($res as $fields){
                $output .= $serie . Gauquelin5::CSV_SEP . implode(Gauquelin5::CSV_SEP, $fields);
            }
            $dest_file = $dest_dir . DS . $groupCode . '.csv';
            file_put_contents($dest_file, $output);
        }
    }
    
    
    // ******************************************************
    /**
        Loads the csv files located in 3-cura-modified/ in arrays
        Auxiliary of self::modified21955()
        @param $src_dir String Directory called 3-cura-modified/ in config
        @return associative array :
                group code => array containing the values of NUM in this group
                group codes are keys of self::GROUPS_1955
    **/
    private static function loadGroups3($src_dir){
        $res = [];
        foreach(self::GROUPS_1955 as $groupCode => [$name, $serie]){
            $res[$groupCode] = [];
            $raw = @file_get_contents($src_dir . DS . $serie . '.csv');
            if($raw === false){
                continue;
            }
            $raw = str_replace('"', '', $raw); // libreoffice adds " and I don't know how to remove them
            $lines = explode("\n", $raw);
            $nlines = count($lines);
            $fieldnames = explode(self::CSV_SEP_LIBREOFFICE, $lines[0]);
            $flip = array_flip($fieldnames);
            for($i=1; $i < $nlines; $i++){
                if(trim($lines[$i]) == ''){
                    continue;
                }
                $fields = explode(self::CSV_SEP_LIBREOFFICE, $lines[$i]);
                $code = $fields[$flip['1955']];
                if($code != $groupCode){
                    continue;
                }
                $res[$groupCode][] = $fields[$flip['NUM']];
            }
        }
        return $res;
    }
    
}// end class    

