#!/usr/bin/bash

#
# Command to export the local database in a postgresql dump
# Must be executed from g5 root directory.
# Environment variables are taken from config.env
# DB dumps are generated in dbdump/ (or in a directory specified in config.env)
# This directory is not versioned, you mut create it
#

if [ $# -ne 0 ]; then
    echo "This command doesn't need argument"
    exit
fi

if [ ! -f "config.env" ]; then
  echo "File config.env does not exist - create it and try again"
  exit
fi

source config.env

if [ ! -d "$PGDUMP_DIR" ]; then
  echo "Directory $PGDUMP_DIR does not exist - create it and try again"
  exit
fi

cd $PGDUMP_DIR

dumpfile="${DB_DBNAME}-$(date +"%Y-%m-%d-%H%M%S").pgdump"
zipfile=$dumpfile.zip

command1="export PGPASSWORD=$DB_PASSWORD"
command2="$PGDUMP_CMD --file $dumpfile -h $DB_HOST -p $DB_PORT -U $DB_USER -n $DB_SCHEMA $DB_DBNAME"
echo "$command1 ; $command2"
$command1
$command2

zip $zipfile $dumpfile
rm $dumpfile

echo "Done"
