#!/usr/bin/bash

#
# Command to import a postgresql dump to dbdump/ (or a directory specified in config.env)
# Must be executed from g5 root directory.
# This directory is not versioned, you mut create it.
#

if [ $# -ne 1 ]; then
    echo "This command needs an argument : "
    echo "the name of the zip file without the .zip extension"
    echo "(dumps are located by default in dbdump/)"
    echo "Ex: $0 db5-2023-01-22-12:53:37.pgdump"
    exit
fi

if [ ! -f "config.env" ]; then
  echo "File config.env does not exist - create it and try again"
  exit
fi

source config.env

if [ ! -d "$PGDUMP_DIR" ]; then
  echo "Directory $PGDUMP_DIR does not exist - create it and try again"
  exit
fi

cd $PGDUMP_DIR

dumpfile=$1
zipfile="$dumpfile.zip"

if [ ! -f "$zipfile" ]; then
    echo "Fichier inexistant: $PGDUMP_DIR/$zipfile"
    exit
fi

unzip "$zipfile"
export PGPASSWORD=$DB_PASSWORD
psql -d $DB_DBNAME -U $DB_USER -h $DB_HOST -p $DB_PORT -c "drop schema $DB_SCHEMA cascade"
psql $DB_DBNAME -U $DB_USER -h $DB_HOST -p $DB_PORT < $dumpfile

rm $dumpfile

echo "Done"
